
window.PAL_AI=(function(){
  function esc(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
  function byMode(mode,v){const T=window.PAL_T;const map={cover:T.rule()+T.corp(v)+T.cover(v),lessonPlan:T.rule()+T.corp(v)+T.ref(v)+T.lessonPlan(v),worksheet:T.rule()+T.corp(v)+T.ref(v)+T.worksheet(v),test:T.rule()+T.corp(v)+T.ref(v)+T.test(v),analysis:T.rule()+T.corp(v)+T.analysis(),report:T.rule()+T.corp(v)+T.report(v),portfolio:T.rule()+T.corp(v)+T.portfolio(v)};return map[mode]||T.all(v)}
  function localAI(kind,v,output){if(kind==='improve'){const text=output.innerText.trim();return `<section class="block"><h2>تحسين محلي</h2><ul><li>تقليل التكرار غير الضروري.</li><li>زيادة وضوح الهدف والإجراء.</li><li>ربط التقويم مباشرة بالمخرجات.</li></ul><pre style="white-space:pre-wrap">${esc(text)}</pre></section>`}if(kind==='generate') return byMode(v.outputMode||'all',v);if(kind==='autopack') return byMode('all',v)+`<section class="block"><h2>ملحق أتمتة</h2><p>تم إكمال الحقيبة بذكاء محلي قاعدي.</p></section>`;return ''}
  async function callAI(v,kind,output,status){const mode=v.aiMode||'local', endpoint=v.apiEndpoint||'', key=v.apiKey||'', model=v.aiModel||'';const prompt='أنت مساعد تربوي تنفيذي. اتبع القاعدة: اعتمد المرجع المتحقق، أصلح الصياغة والتنظيم، أكمل العناصر العملية المطلوبة. البيانات: '+JSON.stringify(v);const tasks={generate:'أنتج المخرج المطلوب بالكامل.',improve:'حسّن النص الحالي الموجود في المخرجات مع الحفاظ على المعنى والوضوح. النص: '+output.innerText.trim(),autopack:'أنتج الحقيبة الكاملة آليًا.'};if(mode==='local'||!endpoint||!key){status.textContent='استخدام الذكاء المحلي القاعدي.';return localAI(kind,v,output)}try{let result='';if(mode==='openai'){const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:model||'gpt-4o-mini',messages:[{role:'system',content:prompt},{role:'user',content:tasks[kind]}],temperature:0.3})});const data=await res.json();if(!res.ok) throw new Error(data.error?.message||data.message||('HTTP '+res.status));result=data?.choices?.[0]?.message?.content||''}else if(mode==='gemini'){const url=endpoint.replace(/\/$/,'')+'/'+(model||'gemini-1.5-flash')+':generateContent?key='+encodeURIComponent(key);const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt+'
'+tasks[kind]}]}]})});const data=await res.json();if(!res.ok) throw new Error(data.error?.message||data.message||('HTTP '+res.status));result=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('
')||''}else if(mode==='anthropic'){const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:model||'claude-3-5-sonnet-latest',max_tokens:2000,system:prompt,messages:[{role:'user',content:tasks[kind]}]})});const data=await res.json();if(!res.ok) throw new Error(data.error?.message||data.message||('HTTP '+res.status));result=(data.content||[]).map(x=>x.text||'').join('
')}else{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key,model:model,prompt:prompt,userTask:tasks[kind],context:v})});const data=await res.json();if(!res.ok) throw new Error(data.error||data.message||('HTTP '+res.status));result=data.output||data.text||JSON.stringify(data,null,2)}if(!result) throw new Error('لم تُرجع الواجهة نصًا صالحًا.');status.textContent='تم استخدام واجهة الذكاء بنجاح.';return `<section class="block"><h2>مخرج ذكاء اصطناعي</h2><div style="white-space:pre-wrap">${esc(result)}</div></section>`}catch(err){status.textContent='تعذر استخدام الواجهة الخارجية: '+err.message+'
تم الرجوع إلى الذكاء المحلي.';return localAI(kind,v,output)}}
  return {byMode,callAI};
})();
