
(function(){
'use strict';
const ids=['teacherName','schoolName','directorateName','subjectName','gradeName','sectionName','termName','yearName','docDate','lessonTitle','unitTitle','lessonTime','outputMode','pageText','extraNotes','aiMode','aiModel','apiEndpoint','apiKey'];
const $=id=>document.getElementById(id);
function vals(){const o={};ids.forEach(id=>o[id]=$(id)?$(id).value:'');return o;}
function hdr(){const v=vals();$('badgeTeacher').textContent='المعلم: '+(v.teacherName||'—');$('badgeSchool').textContent='المدرسة: '+(v.schoolName||'—');$('badgeSubject').textContent='المادة: '+(v.subjectName||'—');$('badgeGrade').textContent='الصف: '+(v.gradeName||'—')+(v.sectionName?' / '+v.sectionName:'');$('docHeader').textContent=v.lessonTitle?('الحقيبة التعليمية — '+v.lessonTitle):'الحقيبة التعليمية والإدارية';$('metaHeader').textContent=[v.subjectName||'—',v.gradeName||'—',v.termName||'—',v.yearName||'—',v.docDate||'—'].join(' | ');$('directorateLineMain').textContent=v.directorateName?('المديرية / المنطقة: '+v.directorateName):'—';}
function saveLocal(){localStorage.setItem(window.PAL_CFG.storageKey,JSON.stringify({form:vals(),output:$('output').innerHTML}));}
function loadLocal(silent){const raw=localStorage.getItem(window.PAL_CFG.storageKey);if(!raw){if(!silent) alert('لا توجد بيانات محفوظة.');return;}const d=JSON.parse(raw);if(d.form){Object.entries(d.form).forEach(([k,v])=>{if($(k)) $(k).value=v;});}if(d.output) $('output').innerHTML=d.output;hdr();if(!silent) alert('تمت الاستعادة.');}
function exportJson(){const b=new Blob([JSON.stringify({savedAt:new Date().toISOString(),form:vals(),output:$('output').innerHTML},null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='pal_final_project_data.json';a.click();URL.revokeObjectURL(a.href);} 
function importJson(file){const r=new FileReader();r.onload=()=>{const d=JSON.parse(r.result);if(d.form){Object.entries(d.form).forEach(([k,v])=>{if($(k)) $(k).value=v;});}if(d.output) $('output').innerHTML=d.output;hdr();alert('تم الاستيراد.');};r.readAsText(file,'utf-8');}
function downloadHtml(){const html='<!DOCTYPE html>
'+document.documentElement.outerHTML;const b=new Blob([html],{type:'text/html;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='المنصة_النهائية_التنفيذية.html';a.click();URL.revokeObjectURL(a.href);}
function defaults(){const m=$('aiMode').value,d=window.PAL_CFG.endpoints;if(m==='openai'&&!$('apiEndpoint').value) $('apiEndpoint').value=d.openai;if(m==='gemini'&&!$('apiEndpoint').value) $('apiEndpoint').value=d.gemini;if(m==='anthropic'&&!$('apiEndpoint').value) $('apiEndpoint').value=d.anthropic;if(m==='custom'&&!$('apiEndpoint').value) $('apiEndpoint').value=d.custom;if(m==='local') $('apiEndpoint').value='';$('aiStatus').textContent='تم ضبط الواجهة على النمط: '+$('aiMode').value;}
function setOutputMode(mode){$('outputMode').value=mode;generate(false);} 
function generate(forceAll){const v=vals();hdr();$('output').innerHTML=window.PAL_AI.byMode(forceAll?'all':(v.outputMode||'all'),v);} 
async function runAI(kind){const v=vals();hdr();const h=await window.PAL_AI.callAI(v,kind,$('output'),$('aiStatus'));if(kind==='improve') $('output').innerHTML += h; else $('output').innerHTML = h;saveLocal();}
function clearOutput(){if(!confirm('سيتم تفريغ المخرجات الحالية. هل تريد المتابعة؟')) return;$('output').innerHTML='<section class="block"><h2>تم التفريغ</h2><p>يمكنك التوليد من جديد الآن.</p></section>';}
function toggleAgent(force){const panel=$('agentWindow');const show=(typeof force==='boolean')?force:panel.classList.contains('hidden');panel.classList.toggle('hidden',!show);}
function bindSmart(){$('smartLessonBtn').addEventListener('click',()=>setOutputMode('lessonPlan'));$('smartWorksheetBtn').addEventListener('click',()=>setOutputMode('worksheet'));$('smartTestBtn').addEventListener('click',()=>setOutputMode('test'));$('smartReportBtn').addEventListener('click',()=>setOutputMode('report'));$('smartAnalysisBtn').addEventListener('click',()=>setOutputMode('analysis'));$('smartPackBtn').addEventListener('click',()=>generate(true));}
function getBridgePayload(){try{return JSON.parse($('bridgePayload').value||'{}')}catch{throw new Error('حمولة الجسر JSON غير صالحة.')}}
async function runBridge(command){const data=await window.PAL_BRIDGE.run($('bridgeUrl').value,$('bridgeToken').value,$('bridgeRole').value,command||$('bridgeCommand').value,getBridgePayload());$('bridgeStatus').textContent=JSON.stringify(data,null,2);return data;}
function bindAgent(){const panel=$('agentWindow'),header=$('agentHeader'),logEl=$('agentLog');window.PAL_AGENT.makeDraggable(panel,header);const ctx={output:$('output'),agentStatus:$('agentStatus'),aiStatus:$('aiStatus'),getVals:vals,saveLocal,loadLocal,exportJson,hdr,setOutputMode,runBridge};$('toggleAgentBtn').addEventListener('click',()=>toggleAgent());$('closeAgentBtn').addEventListener('click',()=>toggleAgent(false));$('minimizeAgentBtn').addEventListener('click',()=>panel.classList.toggle('compact'));document.querySelectorAll('.cmd-btn').forEach(b=>b.addEventListener('click',()=>{$('agentCommandInput').value=b.dataset.cmd;}));$('runAgentCommandBtn').addEventListener('click',async()=>{const cmd=$('agentCommandInput').value;const msg=await window.PAL_AGENT.execute(cmd,ctx);window.PAL_AGENT.log(logEl,'> '+cmd);window.PAL_AGENT.log(logEl,msg);$('agentStatus').textContent=msg;});$('agentCommandInput').addEventListener('keydown',async e=>{if(e.key==='Enter'){e.preventDefault();$('runAgentCommandBtn').click();}});}
function bind(){['teacherName','schoolName','directorateName','subjectName','gradeName','sectionName','lessonTitle','termName','yearName','docDate'].forEach(id=>$(id).addEventListener('input',hdr));$('printBtn').addEventListener('click',()=>window.print());$('saveBtn').addEventListener('click',()=>{saveLocal();alert('تم الحفظ محليًا.');});$('loadBtn').addEventListener('click',()=>loadLocal(false));$('exportBtn').addEventListener('click',exportJson);$('importInput').addEventListener('change',e=>{if(e.target.files[0]) importJson(e.target.files[0]);});$('downloadHtmlBtn').addEventListener('click',downloadHtml);$('bookInput').addEventListener('change',e=>window.PAL_PDF.loadPdf(e.target.files[0],$('pageIndicator'),$('pdfCanvas')).catch(err=>alert('تعذر فتح PDF: '+err.message)));$('prevPageBtn').addEventListener('click',()=>window.PAL_PDF.prev($('pageIndicator'),$('pdfCanvas')));$('nextPageBtn').addEventListener('click',()=>window.PAL_PDF.next($('pageIndicator'),$('pdfCanvas')));$('extractTextBtn').addEventListener('click',async()=>{$('pageText').value=await window.PAL_PDF.extract();});$('copyPageTextBtn').addEventListener('click',async()=>{const txt=$('pageText').value||'';if(!txt){alert('لا يوجد نص لنسخه.');return;}await navigator.clipboard.writeText(txt);alert('تم النسخ.');});$('generateBtn').addEventListener('click',()=>generate(false));$('generateAllBtn').addEventListener('click',()=>generate(true));$('clearBtn').addEventListener('click',clearOutput);$('aiMode').addEventListener('change',defaults);$('aiGenerateBtn').addEventListener('click',()=>runAI('generate'));$('aiImproveBtn').addEventListener('click',()=>runAI('improve'));$('aiAutoPackBtn').addEventListener('click',()=>runAI('autopack'));$('bridgeRunBtn').addEventListener('click',()=>runBridge());$('bridgeHealthBtn').addEventListener('click',()=>runBridge('health_check'));$('bridgeAuditBtn').addEventListener('click',()=>runBridge('get_audit_tail'));bindSmart();bindAgent();}
document.addEventListener('DOMContentLoaded',()=>{bind();loadLocal(true);defaults();hdr();window.PAL_PDF.update($('pageIndicator'));});
})();
